name: API Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "api-server/**/*.rb"
      - "api-server/**/*.rake"
      - "api-server/**/Gemfile"
      - ".github/workflows/api-test.yaml"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.36
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: practice_for_eav_anti_pattern_test
          TZ: "Asia/Tokyo"

    steps:
      # リポジトリのクローン
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Copy env file
        working-directory: api-server
        run: cp .env.test .env

      # NOTE: Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          ruby-version: 3.4
          bundler-cache: true
          working-directory: api-server

      - name: Run Tests
        working-directory: api-server
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: RAILS_ENV=test bundle exec rspec
